import { describe, expect, test } from "bun:test";
import { createHash } from "crypto";
import { linkSync, mkdtempSync, mkdirSync, readFileSync, symlinkSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { spawnSync } from "child_process";
const repo=join(import.meta.dir,"..");const scripts=join(repo,"skills","sprite-workflow","scripts");
const imagePython=[process.env.SPRITE_WORKFLOW_PYTHON,"/usr/bin/python3","python3"].find(candidate=>candidate&&spawnSync(candidate,["-c","import PIL"],{encoding:"utf8"}).status===0)??"python3";
const run=(name:string,args:string[])=>spawnSync(imagePython,[join(scripts,name),...args],{encoding:"utf8"});
const hash=(p:string)=>createHash("sha256").update(readFileSync(p)).digest("hex");
const png=(p:string,w=4,h=4,color="(255,0,0,255)")=>{const r=spawnSync(imagePython,["-c",`from PIL import Image\nImage.new('RGBA',(${w},${h}),${color}).save(${JSON.stringify(p)},'PNG')`]);expect(r.status).toBe(0)};
const json=(p:string,v:unknown)=>writeFileSync(p,JSON.stringify(v,null,2));
describe("sprite workflow security",()=>{
 test("rejects traversal job IDs before publication",()=>{const d=mkdtempSync(join(tmpdir(),"sprite-job-sec-"));const r=run("new-job.py",["--root",join(d,"state"),"--target-repo",d,"--job-id","../escape","--title","x"]);expect(r.status).toBe(1);});
 test("rejects traversal, symlink, and hardlinked production frames",()=>{const d=mkdtempSync(join(tmpdir(),"sprite-manifest-sec-"));mkdirSync(join(d,"frames"));const outside=join(d,"outside.png");png(outside);const base=(file:string)=>({frameSize:[4,4],frameCount:1,states:["idle"],frames:[{file,state:"idle",index:0,sha256:hash(outside),dimensions:[4,4]}],provenance:{sourceLane:"manual",usage:"production-approved"}});const m=join(d,"manifest.json");json(m,base("../outside.png"));expect(run("validate-manifest.py",[m]).status).toBe(1);symlinkSync(outside,join(d,"frames","link.png"));json(m,base("frames/link.png"));expect(run("validate-manifest.py",[m]).status).toBe(1);linkSync(outside,join(d,"frames","hard.png"));json(m,base("frames/hard.png"));expect(run("validate-manifest.py",[m]).status).toBe(1);});
 test("refuses ambiguous auto scales and detects tampered snap reports",()=>{const d=mkdtempSync(join(tmpdir(),"sprite-snap-sec-"));const solid=join(d,"solid.png");png(solid,16,16);expect(run("snap-native-grid.py",[solid,"--mode","auto","--output",join(d,"out.png"),"--report",join(d,"auto.json")]).status).toBe(2);const source=join(d,"source.png");const gen=spawnSync(imagePython,["-c",`from PIL import Image\nim=Image.new('RGBA',(4,4));im.putdata([(x*40,y*40,0,255) for y in range(4) for x in range(4)]);im.resize((16,16),Image.Resampling.NEAREST).save(${JSON.stringify(source)},'PNG')`]);expect(gen.status).toBe(0);const report=join(d,"report.json");expect(run("snap-native-grid.py",[source,"--mode","explicit","--grid-size","4","--output",join(d,"native.png"),"--report",report]).status).toBe(0);const forged=JSON.parse(readFileSync(report,"utf8"));forged.agreement=.5;json(report,forged);expect(run("validate-snap-report.py",[report]).status).toBe(1);});
 test("detects atlas pixel and geometry tampering",()=>{const d=mkdtempSync(join(tmpdir(),"sprite-atlas-sec-"));mkdirSync(join(d,"frames"));const f=join(d,"frames","f.png");png(f,3,3);const m=join(d,"source.json");json(m,{provenance:{usage:"production-approved"},frames:[{id:"idle-0",state:"idle",index:0,file:"frames/f.png",sha256:hash(f),dimensions:[3,3],anchor:[1,2]}]});const atlas=join(d,"atlas.png"),am=join(d,"atlas.json");expect(run("assemble-approved-atlas.py",[m,"--output",atlas,"--atlas-manifest",am]).status).toBe(0);const forged=JSON.parse(readFileSync(am,"utf8"));forged.frames[0].rect=[0,0,2,2];json(am,forged);expect(run("validate-atlas-manifest.py",[am]).status).toBe(1);});
});
